DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS events;

CREATE TABLE members (
  id SERIAL4 PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE events (
  id SERIAL4 PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  time TIMESTAMP NOT NULL
);
